# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  inputs,
  outputs,
  lib,
  config,
  pkgs,
  system,
  ...
}: {
  networking.hostName = "bobby";

  system.stateVersion = "23.11";

  networking.networkmanager.enable = true;

  environment.systemPackages = [inputs.alejandra.defaultPackage.${system} pkgs.pulseaudio];

  imports = [
    ../common
    ../common/features/pipewire.nix
    ../common/features/hyprland.nix
    ./hardware
  ];
}
