# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  inputs,
  outputs,
  lib,
  config,
  pkgs,
  system,
  ...
}: {
  networking.hostName = "bobby";

  system.stateVersion = "23.11";

  #networking.networkmanager.enable = true;

  environment.systemPackages = [pkgs.pulseaudio];

  # for blue ray
  boot.kernelModules = ["sg"];

  imports = [
    ../common/nixos.nix
    ../common/features/pipewire.nix
    ../common/features/hyprland.nix
    ../common/features/virtualisation.nix
    ./hardware
  ];

  virtualisation.enable = true;
}
