# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  inputs,
  outputs,
  lib,
  config,
  pkgs,
  ...
}: {
  networking.hostName = "bobby";

  system.stateVersion = "23.11";

  imports = [
    ../common
    ../common/features/pipewire.nix
    ../common/features/hyprland.nix
    ./hardware
  ];
}
