keys:
  - &users:
    - &alwin alwin@stockinger.tech
  - &hosts:
    - &alex age1n0lqflctwvj2krxq3u06pzajqx3qx72vdnpca8dq6f4dlzm4pdxqqr6tza
creation_rules:
  - path_regex: hosts/alex/secrets.yaml
    key_groups:
    - pgp:
      - *alwin
      age:
      - *alex
  - path_regex: hosts/alex/docker-compose.yaml
    encrypted_regex: CLOUDFLARE_API_KEY
    key_groups:
    - pgp:
      - *alwin
      age:
      - *alex
