keys:
  - &users:
    - &alwin 0xB348B2BDC7E49D64
  - &hosts:
    - &alex age1n0lqflctwvj2krxq3u06pzajqx3qx72vdnpca8dq6f4dlzm4pdxqqr6tza
creation_rules:
  - path_regex: ".*.yaml"
    key_groups:
      - pgp:
          - *alwin
        age:
          - *alex
