keys:
  - &users:
    - &alwin 0xB348B2BDC7E49D64
  - &hosts:
    - &alex age1n25hcrrsykahvaw2xjy5sf6skc6092g7a0t8mnpx8n874camh3nq5qx7ye
creation_rules:
  - path_regex: ".*.yaml"
    key_groups:
      - pgp:
          - *alwin
        age:
          - *alex
