# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ inputs, lib, config, pkgs, ... }: {
  options = {
    custom.desktop.enable =
      lib.mkEnableOption "enables a desktop enviroment via hyprland";
  };

  config = lib.mkIf config.custom.desktop.enable {
    programs.hyprland = {
      enable = true;
      #package = inputs.hyprland.packages."${pkgs.system}".hyprland;
    };
  };
}
