version: "3"
services:
    traefik:
        image: traefik
        container_name: traefik
        volumes:
            - /data/traefik/letsencrypt:/letsencrypt
            - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            - 80:80
            - 443:443
        environment:
            - ENC[AES256_GCM,data:3bUxVlPEckL5dMQrYP3Aqd2p2Az/HCN5V+mw+YRs1HNutKB2Ah8=,iv:Rxg/FVdjM9L5YEZD6+KEhWVeVnBlbJQRdPb/lEuN5zQ=,tag:JsWPsYxzjUd/mpEg+2SJ3A==,type:str]
            - ENC[AES256_GCM,data:5fzs9Rso6MMSKWidmwwBNoOPm/tXprdQLC8TlvLWxEFS2NMk87APy+Rxfro9xWX3xrzBs2AJxw0=,iv:K/iT6W18S7bmrcGRORUmUkJgL4ohEYZi3f0TVAEyHXo=,tag:ROMnQlkci/lZys2moNx2sg==,type:str]
        command:
            - --providers.docker=true
            - --entrypoints.web.address=:80
            - --entrypoints.web.http.redirections.entryPoint.to=websecure
            - --entrypoints.web.http.redirections.entryPoint.scheme=https
            - --entrypoints.websecure.address=:443
            - --certificatesresolvers.cloudflare.acme.dnschallenge=true
            - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
            - --certificatesresolvers.cloudflare.acme.dnschallenge.disablepropagationcheck
            - --certificatesresolvers.cloudflare.acme.email=alwin@stockinger.tech
            - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
            - --certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
    actual:
        image: actualbudget/actual-server:latest-alpine
        container_name: actual-compose
        ports:
            - 5006:5006
        labels:
            - traefik.enable=true
            - traefik.http.routers.nginx.rule=Host(`budget.stockinger.tech`)
            - traefik.http.routers.nginx.tls.certresolver=cloudflare
            - traefik.http.routers.actual-server.entrypoints=websecure
            - traefik.http.services.actual-server.loadbalancer.server.port=5006
        volumes:
            - type: bind
              source: /data/actual/data
              target: /data
        restart: unless-stopped
    jellyfin:
        image: jellyfin/jellyfin
        container_name: jellyfin
        user: uid:gid
        network_mode: host
        volumes:
            - /data/jellyfin/config:/config
            - /data/jellyfin/cache:/cache
            - type: bind
              source: /data/media
              target: /media
        restart: unless-stopped
        # Optional - alternative address used for autodiscovery
        # environment:
        #     - JELLYFIN_PublishedServerUrl=http://example.com
        # Optional - may be necessary for docker healthcheck to pass if running in host network mode
        extra_hosts:
            - host.docker.internal:host-gateway
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n0lqflctwvj2krxq3u06pzajqx3qx72vdnpca8dq6f4dlzm4pdxqqr6tza
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNzQ4RW4vZ3NrNE9xVXpq
            bFlkWEF4azRrOGZ2bmd4STFieGhUT3VrT0RVCnZsQWRHYWxjbUhJclJ4QklkWmF6
            RDdPeHBpTGwzbjV2WWZiNzRPNXNCd1UKLS0tIHMxeW9KUkhwYVAwQ2xjQnM2b3VI
            UTgrcU9NaGZnNWtmaWJ1VFBNSXlwREUKpx0893EyKPe74WjzqjxIyE14P/xDA5cK
            f63mJ7v8GlVTAOaH87U1TORdJPmfEP3I9+MZcDQvELLdqq9JOZY1lQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-16T15:43:52Z"
    mac: ENC[AES256_GCM,data:8rx3Fg4q2FvOv1Mo1puM/qrnO3ESElTXRUks+U5j/LCyBcyciadBy0eckmy2nH9Re/o03PIiEoc+kpw1Z/bMDZVgJzKUfuIetBF+NuLTCDIpkDUaUSPKISQt0bjH1MA/i5qKdHbm1bEa+Ql2EkzrPxm18mUo7B1bZBJzdQwk6Cg=,iv:uTvejyzqJkngT55j2DwHOlnbdWHTlzIs1K7hftbpH8Y=,tag:GtOu8UW7q2kCFiGmNLdyDg==,type:str]
    pgp:
        - created_at: "2024-03-16T15:43:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0nh7MUnONy2AQ//QHyS2rlNWF4MqbmOF/RRYC944I9pnUxuglVMmReJBHYD
            pvmyENP2YRdFBMlpW4dXwknHstnnJobzmytKyz3GmOHunMFBd6ZC44+dGaMG87c8
            QCVdtMdxXATIAHkCKRJvzPFvzYZYj9YUNtvHsrLUl9fqBuZV2RNVCKpL/17asPU1
            ubnXX50rFBdhE7NlHw+yeOb2TzP9j1v2l/iVIJ4XVFOKRk0wbb7brOKNEZO7x5Re
            e8bT//n9gkSkQ9vybhryB2gcP0s1IULYIPsxG+CxQVRqhYB+6Vadl9rU70u3CdIK
            Qz6zbaYpu9RIqJ7AM17bWBSiR6XoyBFJKOvyGHYTCmXieohP8nDSQ3icPst7RZYY
            QtsaXwL3YgrlZJisJ1gtN1Dzw03CvP0tLRQPMzU8VeVoCdaxUYRnJ+RmeMRD2FTX
            ZCyngKvoW7dpARFBHm/tIUQiAmf+7XlUg+FJ+FY3xbzpvry443lQXsBSszT0IBNm
            IiRZVYbKJrpnemm0bUnNYSDclKHZdW4gJ2p1rKwxXsbdEoO2USoRNqGtvVD2faei
            Ym4nkyEjdmoGYlPhAy9SA+ymNoW3qhFqoRxBHrXnKV0Dn8xuBM4DUynDxiKwkqG6
            7mfWnN1A6lwrrBkXM2F8EyniAK9nh1QzY4LLSdSOk4MRDMY1aDlifbQBdubqi0fS
            XAF10TA4OaHR2gpO9WZaYOVKFh5DYOF7qlK3V0uBRTQEsHZdftXzdP2hSm7EU8jy
            Ar1QmLboS8eWEim++HRxg/E6kL3KpmmUk+V/AsxOneClFRxBkk+54t9/K8ka
            =Et3b
            -----END PGP MESSAGE-----
          fp: "0xB348B2BDC7E49D64"
    encrypted_regex: environment
    version: 3.8.1
